# Generated by Django 5.1.7 on 2025-04-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='tag',
            field=models.CharField(choices=[('D', 'Django'), ('F', 'Flask'), ('P', 'Basic Python'), ('A', 'RESTful APIs'), ('B', 'Databases'), ('ORM', 'Object-Relational Mapping'), ('SQL', 'SQL'), ('ML', 'Machine Learning'), ('AI', 'Artificial Intelligence'), ('TDD', 'Test-Driven Development'), ('CS', 'Data Structures & Algorithms'), ('P', 'Functional Programming'), ('CI/CD', 'Continuous Integration / Continuous Deployment'), ('U', 'Usability'), ('S', 'Security'), ('AIO', 'Async Programming / AsyncIO'), ('C', 'Cloud Computing'), ('R', 'RPA (Robotic Process Automation)'), ('GIT', 'Version Control (Git)'), ('T', 'Testing'), ('DHT', 'Technical Skills Development')], max_length=5),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentorship.mentorship')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mentorship.mentorship')),
            ],
        ),
    ]
